### ISSUE TITLE
Headings preview error, please solve it.

### ISSUE THREAD

**Issue by Ahv3-Christian** [Emrie-Candera/Bubble-Space-Theme#11]
hi, excuse me, i found an error.
i would like them to solve it, i just solved it like this.      
: 1

THIS ERROR: Headings cannot be preiviewed

![Screenshot_2](https://user-images.githubusercontent.com/99576219/154825680-421a1212-8412-4c1c-b772-141692e731d4.png)

AND NOW
![Screenshot_1](https://user-images.githubusercontent.com/99576219/154825686-7773be06-1a86-4841-b7df-74feb78d7df2.png)

WHAT I MODIFIED TO BE ABLE TO USE THE THEME
![h1](https://user-images.githubusercontent.com/99576219/154825690-0dc0ea85-6e8e-42cc-bb2f-788f8c3e656e.png)
![markmind](https://user-images.githubusercontent.com/99576219/154825688-b875404b-ec2a-44b4-879e-40c90ad21fd0.png)

**Comment by Emrie-Candera** [comment]
Do the headers only not show in the markmind plugin? (From my understanding the issue is that the headers are not shown in the markmind cards). I don't use the plugin so I'd have to check but for the next release, I made adjustments according to the modifications you shared so it would be usable to you. 

target date is next Saturday as I'll be adding this along with the Style Settings Support and other changes

**Comment by Emrie-Candera** [comment]
btw what app are you using to open the css and what theme? It looks so good 🥺
