### ISSUE TITLE
Kindly remove the vault name and Obsidian version number in title bar

### ISSUE THREAD

**Issue by gigazen** [Emrie-Candera/Bubble-Space-Theme#4]
Hi Emrie, I am using your bubble space theme for Obsidian and it is good so far. But can you please remove the vault name and Obsidian version number in title bar like the discordian theme. Also please fix the backlinks at the bottom that are coming up covering the texts in reading mode.

**Comment by Emrie-Candera** [comment]
Hi! I just added the option to toggle this on using the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings#:~:text=This%20plugin%20allows%20snippet%2C%20theme,string%2C%20and%20color%20CSS%20variables.) as of [v1.4](https://github.com/Emrie-Candera/Bubble-Space-Theme/releases/tag/v1.4). I did not make it the default look since I personally prefer having it there. 

If you do not want to use a plugin simply remove `.hide-title` in lines 2120-2126. 😄

**Comment by gigazen** [comment]
Ok friend. Thank you very much.
