### ISSUE TITLE
Pane Title bar design crush

### ISSUE THREAD

**Issue by ab-dauletkhan** [Emrie-Candera/Bubble-Space-Theme#9]
I use **Sliding pane plugin**, and when I open another pane (Cmd + Click), the **_Pane title bar has grey shadow effect on the blue_**. I attached a screenshot of it. @Emrie-Candera 
![image](https://user-images.githubusercontent.com/80996807/151915445-3f3e7b40-8769-40e5-8e5b-f67c73ddf3f7.png)
Hope, you guys fix it, since I truly like bubble space theme, the only _distracter_ is this shadow effect or something else.

**Comment by Emrie-Candera** [comment]
Thanks for bringing this up. I don't use the plugin so wasn't aware of this issue. btw you don't need to ping InterstellarRaccoon as I am the theme's designer and they just contributed a fix before. 😅 

This will be fixed in the next update that I'm working on right now which will be released today or tomorrow

**Comment by Emrie-Candera** [comment]
now solved in [v1.5](https://github.com/Emrie-Candera/Bubble-Space-Theme/releases/tag/v1.5) ❤️
